### ISSUE TITLE
prepublish failing

### ISSUE THREAD

**Issue by illiteratewriter** [cht8687/react-hover#22]
$ parallelshell -w "npm run build:dist -s" "npm run build:example -s" "npm run build:bower -s"
    child_process.js:403
        throw new TypeError('"cwd" must be a string');
        ^

    TypeError: "cwd" must be a string
        at normalizeSpawnArguments (child_process.js:403:11)
        at exports.spawn (child_process.js:496:38)
        at C:\Users\manu\Desktop\react-hover\node_modules\parallelshell\index.js:104:17
        at Array.forEach (<anonymous>)
        at Object.<anonymous> (C:\Users\manu\Desktop\react- 
    hover\node_modules\parallelshell\index.js:100:6)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Both `npm install` and `yarn` is throwing this error. npm version 5.6.0 and yarn version 1.3.2 
using Windows 10

**Comment by cht8687** [comment]
Hi @illiteratewriter, the `prepublish`is part of the `npm publish` hook which I used to publish this module to NPM. I am not sure why do you need run this command yourself. But have you installed `parallelshell`? what's your `npm` version?

**Comment by illiteratewriter** [comment]
`npm` version is 5.6.0. `prepublish` is also run when we do `npm install` or running `yarn`.  So I think it is being run when I do `npm install` also though there is no need to do so. There's a new script called `prepublishOnly` and `prepublish` has been deprecated apparently. So can I change it to the new `prepublishOnly` and do a PR?

([npm prepublish deprecation note](https://docs.npmjs.com/misc/scripts#deprecation-note))

**Comment by cht8687** [comment]
sure，PR welcome！
